Implement coercers
RateGravity/type-shift pull request #24
Opened 2021-06-04 16:38 UTC by pignatenko

## TL;DR

The point of this PR is to create syntactic sugar for handling Typescript's null strictness in a safe way to prevent pedantic mistakes for mixing up `null` and `undefined` when it doesn't truly matter.

## Empty type

We create a new type called `Empty` exposed as a `t.empty` converter which allows you to pass `undefined` or `null` values.

## Coercers

Building on this we create a concept called a `coercer` which is exposed as `t.coerce` this allows you to input a set of converters and a value, if any converter successfully passes it returns the given value.

We bake in 2 default coercers called `emptyAsNull` and `emptyAsUndefined`. These coercers allow `empty` values but return `null` and `undefined` respectfully.

## CONTROVERSIAL SECTION -- optional

The idea here is to then pass on the `empty` concept into `t.optional`.

This PR modifies `t.optional` to coerce `null` into `undefined` and creates a `t.strictOptional` which retains the original behavior.

This is arguably the most semantic way to handle this and preserves the original intent that this library is an `undefined` based library following the MS standard but can seamlessly interoperate with libraries that follow a null standard or a mixed standard.

This is probably the most controversial change here, there are obviously other solutions to organizing this. Let me know what you guys think.

2021-06-04 16:50 UTC, RoboCafaz commented on src/basic-types.ts
> +const EmptyConverter: Converter<Empty> = NullConverter.or(UndefinedConverter);
The name `Empty` has me thinking about `[]` and `{}`. Is there a better name for `null | undefined`?

2021-06-04 16:51 UTC, pignatenko commented on src/basic-types.ts
> +const EmptyConverter: Converter<Empty> = NullConverter.or(UndefinedConverter);
`nothing`?

2021-06-04 16:53 UTC, pignatenko commented on src/basic-types.ts
> +const EmptyConverter: Converter<Empty> = NullConverter.or(UndefinedConverter);
Also `none`

2021-06-04 16:56 UTC, RoboCafaz commented on src/basic-types.ts
> +const EmptyConverter: Converter<Empty> = NullConverter.or(UndefinedConverter);
Any of those would work for me. Maybe put it out for a poll on #dev?

2021-06-04 16:56 UTC, RoboCafaz commented on src/coercers.ts
> +export const emptyAsUndefined: Converter<Empty> = coerce([empty], undefined);
TSDocs pls

2021-06-04 16:57 UTC, qcharlieshi commented on src/basic-types.ts
> +const EmptyConverter: Converter<Empty> = NullConverter.or(UndefinedConverter);
We use `none` in the `optional` lib in core-lib

2021-06-04 16:57 UTC, RoboCafaz commented on src/basic-types.ts
> +export type Empty = null | undefined;
TSDocs pls

2021-06-04 16:58 UTC, RoboCafaz commented
I'm okay with the baseline change to optional. Just make sure this is a major version release and it gets communicated in release notes.

2021-06-04 16:58 UTC, RoboCafaz approved these changes
Just naming/doc nits. Functionality looks good.

2021-06-04 16:59 UTC, pignatenko commented on src/basic-types.ts
> +const EmptyConverter: Converter<Empty> = NullConverter.or(UndefinedConverter);
@qcharlieshi That sounds like a good reason to go with `None`/`none` then.

2021-06-04 17:12 UTC, pignatenko commented
> Just naming/doc nits. Functionality looks good.

TSDocs/naming fixed. Will wait for consensus regarding `optional`.

2021-06-04 17:20 UTC, chris-pardy requested changes

2021-06-04 17:20 UTC, chris-pardy commented on src/decorators.ts
> +}
From a versioning perspective I'd prefer we went the other way and introduced a coerced optional rather than a changing the behavior of optional. In particular there are many places where we use `null` to mean "I don't know" and undefined to mean don't update this field. Something like: `{ downPayment?: null | number }` which would break in this case as the nulls would become undefindes.
Also in general I think this library should strive for a set of strict core types and then compose them into less strict types, the core boolean, string, and number converters don't do this and I think it was a mistake.

As far as making breaking changes go I'd like to avoid that if possible and just document them in issues instead. This whole library is due for a major facelift in V1. In particular there are just fundamental mistakes that need to be revisited like relying on thrown errors to indicate failures, and treating missing and undefined values as equivalent.

2021-06-04 17:30 UTC, pignatenko commented on src/decorators.ts
> +}
So reverting `t.strictOptional` to `t.optional` and creating a `t.coercedOptional` would rectify your objections? I am also trying to avoid paperwork/process that comes with major version changes etc.

2021-06-04 17:31 UTC, RoboCafaz commented on src/decorators.ts
> +}
I'm also okay with this.

2021-06-04 17:32 UTC, chris-pardy commented on src/decorators.ts
> +}
Short answer: yes.
Long answer:
I agree with the idea of having this version of optional be the "normal version you use" but I think we should avoid bumping this library to V1 for this.

2021-06-04 17:37 UTC, pignatenko commented on src/decorators.ts
> +}
Alright I'll change this up and we can put the breaking functionality as part of the issues for V1.

2021-06-04 17:37 UTC, kstrickland0612 commented on src/decorators.ts
> +}
I'm also in favor of maintaining `t.optional`'s current behavior and handling the coercion in a new converter.

2021-06-04 17:38 UTC, chris-pardy commented on src/coercers.ts
> +  }, name);
from an error readability perspective consider defining this as:
```ts
const predicate = converters.reducer((c1, c2) => c1.or(c2));
return predicate.pipe(() => value, displayValue(value));
```

This way the error thrown will be the one from the union, which tries it best to select a specific error.

2021-06-04 17:39 UTC, chris-pardy commented on src/coercers.ts
> +export const coerce = <V>(converters: Array<Converter<any>>, value: V): Converter<V> => {
I would type this as `converters: [ConverterFunction<any>, ...ConverterFunction<any>[]]` to enforce a minimum of 1 converter.

2021-06-04 17:44 UTC, chris-pardy commented on src/coercers.ts
> +  }, name);
For something like `t.coerce([t.string, t.null], 'something')({ notString: true })` then the error will be `At $ expected string | null but was { notString: true }`. However for something like: `t.coerce([t.strict({ isString: t.boolean }), t.null], 'something')({ notString: true })` the error if you do the or joining of the input converters will be: `At $.isString expected boolean but was undefined`

2021-06-04 18:10 UTC, chris-pardy commented on src/decorators.ts
> +}
@pignatenko feel free to comment on #25 with any ideas.

2021-06-04 18:11 UTC, chris-pardy commented on src/coercers.ts
> +export const coerce = <V>(converters: Array<Converter<any>>, value: V): Converter<V> => {
Yes, you would need an unwrap code but again I'm ok with that.

2021-06-04 18:12 UTC, chris-pardy commented on src/coercers.ts
> +export const coerce = <V>(converters: Array<Converter<any>>, value: V): Converter<V> => {
One thing to keep in mind is that `t.coerce(t.string, 3)` is behaviorally equivalent to `t.string.pipe(() => 3)`

2021-06-04 20:11 UTC, pignatenko commented on src/coercers.ts
> +export const coerce = <V>(converters: Array<Converter<any>>, value: V): Converter<V> => {
I ended up doing type enforcement as the shortest path forward. Array wrapping would be a useful addon, but I am unsure of the perf due to how we use errors, so to keep things speedy for now and to resolve how V1 looks explicit arrays it is.

2021-06-04 20:12 UTC, pignatenko commented on src/coercers.ts
> +  }, name);
I end up doing this, the perf hit is similar in the general case, in the exceptional case the custom logic performs better but it's not worth it losing error resolution and adding maintinance.

2021-06-04 20:14 UTC, pignatenko commented on src/decorators.ts
> +}
@kstrickland0612 @chris-pardy @RoboCafaz `optional` has been reverted and this functionality has become a "choose your own adventure" for now that maps to the coercer concepts.

`t.noneable` will pass `null` and `undefined` thru.
`t.noneableAsNull` will coerce to `null`.
`t.noneableAsUndefined` will coerce to `undefined`.

2021-06-04 20:26 UTC, chris-pardy commented on src/coercers.ts
> +  return predicate.pipe(() => value, `${predicate.name} -> ${displayValue(value)}`);
use `predicate.displayName` for the correct value.

2021-06-07 16:46 UTC, pignatenko commented on src/coercers.ts
> +export const coerce = <V>(converters: Array<Converter<any>>, value: V): Converter<V> => {
Had to bump rollup dts plugin because it was failing to parse TS4.2

2021-06-07 16:53 UTC, chris-pardy approved these changes
@pignatenko approving, but I'd love your take on how this plays into the whole conversation about:
`t.optional(t.string.default(() => 'empty'))` for instance if I did: `t.noneableAsNull(t.string.default(() => 'empty'))(undefined)` what would I get?

2021-06-07 16:54 UTC, chris-pardy commented on src/decorators.ts
> +): Converter<Result | null, Input | undefined> {
I think these types are: `<Result | null, Input | null | undefined>`

2021-06-07 16:54 UTC, chris-pardy commented on src/decorators.ts
> +): Converter<Result | undefined, Input | undefined> {
I think these types are `<Result | undefined, Input | null | undefined>`

2021-06-07 16:54 UTC, chris-pardy commented on src/decorators.ts
> +): Converter<Result | None, Input | undefined> {
I think these types are `<Result | None, Input | None>`

2021-06-07 17:31 UTC, pignatenko commented
> @pignatenko approving, but I'd love your take on how this plays into the whole conversation about:
> `t.optional(t.string.default(() => 'empty'))` for instance if I did: `t.noneableAsNull(t.string.default(() => 'empty'))(undefined)` what would I get?

So conceptually speaking default creates a type of 'coercer' really. Functionally speaking default creates a functor in the call chain that replaces missing values with a default. Optional creates a functor in the call chain that allows missing values. 

If we are to think of this functionally as the pure function of a monad Option looks like this: (assume `none` is a cached instance of `None` representing nothingness, and `Some` is just a `.value` holder. 

```
  const option = (value) => {
    if ((value === null) || (value === undefined)) {
      return none;
    }
    return new Some(value)
  }
```
Then default looks like this:

```
  const default = (defaultValue) => (value) => {
    if ((value === null) || (value === undefined)) {
      return new Some(defaultValue);
    }
    return new Some(value)
  }
 ```
 
 Our problem here is `optional` is actually `default(none)`. If we're talking a purely functional interface I would say it's up to the lib user to organize their code to achieve this, it's basically the way it works in all languages as the principle of least surprise.
 
 If we are talking about a declarative OO chained this-return interface, all we need to do is ensure that we create the actual converter pipeline lazily and that `default` is always at the top of the call chain so that we can refuse to re-apply in the special `.optional` case. This is typical of such interfaces.
 
 Right now our problem is that we're mixing our metaphors at the very top level and typical library usage expectations are different in different cases. 
 
e.g.

 I wouldn't expect `t.optional(t.default('empty')(t.string))` to return 'empty' because of just FP.


 I wouldn't expect `t.string.optional.default(() => 'empty')` or `t.string.default(() => 'empty').optional`  to return `undefined` because of OO expectation and how many similar libraries typically have resolved this. (e.g. joi, open API spec, etc).
 
 I support being able to use an FP and an OO interface for declaring things.

2021-06-07 17:39 UTC, merged